apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: jenkins
  namespace: default
spec:
  rules:
  - host: jenkins
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
status:
  loadBalancer:
    ingress:
    - {}
